Adds a ping to see if the Xbox is on or off
arcreative/homebridge-xbox-one pull request #4
Opened 2016-10-06 23:46 UTC by dustinrue

Simply adds a ping to determine Xbox state. There is a period of time after the Xbox is "off" that it'll still reply to ping though.

2016-10-16 17:09 UTC, arcreative commented
Looks cool, can you pull the IP off of this.xbox.ip instead of setting a new variable?  Also, can you extract the ping anonymous function into one called `getPowerState` to match the convention used in `setPowerState`?

2016-10-21 19:48 UTC, dustinrue commented
I hope the changes are what you were looking for. I might add the ping to a timer similar to homebridge-wol so the plugin can update apps when the power state changes.

2016-10-24 03:49 UTC, arcreative requested changes
Perfect!  Just remove that little white space and squash commits, and I'll merge :-)

2016-10-27 17:32 UTC, arcreative approved these changes

2016-10-27 17:33 UTC, merged